name: Auto Merge Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_KEY }}

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.NAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git remote add upstream https://github.com/mcMMO-Dev/mcMMO

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories

      - name: Configure Git with Secret
        run: |
          git config --global user.signingkey ${{ secrets.RELEASE_KEY }}

      - name: Push changes
        run: git push origin master

      - name: Cleanup
        run: |
          git remote remove upstream